services:
  web:
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
    container_name: "rar"
    ports:
      - "8080:8080"
  redis:
    image: "redis/redis-stack-server"
    container_name: "redis"
    hostname: "redis-test"